### ISSUE TITLE
Error while installing LinearInterpolators.

### ISSUE THREAD

**Issue by assia855** [emmt/LinearInterpolators.jl#3]
Thank you professor for providing such packages to the public.
Can you allow me please with the right commands to install LinearInterpolators and nterpolationKernels. It seems as there's a problem version.

(StarGenerated) pkg> add https://github.com/emmt/LinearInterpolators.jl
   Updating git-repo `https://github.com/emmt/LinearInterpolators.jl`
  Resolving package versions...
ERROR: Unsatisfiable requirements detected for package InterpolationKernels [16730964]:
 InterpolationKernels [16730964] log:
 ├─possible versions are: 0.2.0 or uninstalled
 ├─InterpolationKernels [16730964] is fixed to version 0.2.0
 └─restricted to versions 0.1 by LinearInterpolators [2fc109c4] — no versions left     
   └─LinearInterpolators [2fc109c4] log:
     ├─possible versions are: 0.1.0 or uninstalled
     └─LinearInterpolators [2fc109c4] is fixed to version 0.1.0

**Comment by emmt** [comment]
I introduced a lot of changes in InterpolationKernels and did not correctly manage the compatibilities, this should be fixed now. I will update LinearInterpolators to work with the last version of InterpolationKernels as soon as possible.

**Comment by assia855** [comment]
We really appreciate your awesome efforts. Thank you so much.
I was wondering if there's a way to have the previous  stable version. If there's a way can you share it with me please.

**Comment by emmt** [comment]
This is exactly what I attempted to do with this.  Unfortunately, it seems that version restrictions only work automatically with official Julia packages which is not yet the case of `InterpolationKernels` and  `LinearInterpolators`.  This means that you have to specify yourself that you want to stick to a given version of `InterpolationKernels` that is compatible with `LinearInterpolators`.  This can be done by using a specific **environment** with Julia package manager (documented [here](https://pkgdocs.julialang.org/)). A Julia environment is a way to specify a list of packages (possibly with version restrictions) you want to work with.  You may have as many environments as you want (they will automatically share the same code if possible) but a Julia session works with a given environment at a time (it is possible to switch the environment by a activating another one but only one environment is active at a time).

I tried to figure out a concrete working example for you.  Starting from scratch, you first have to create a new Julia environment for your project/work that requires `LinearInterpolators`.  You have to decide the name and location (directory) of this environment, for instance `SomeDir/SomeProject` where `SomeDir` is a directory writable by you (the current directory if none specified) `SomeProject` is the name of the new environment, the environment files (`Manifest.toml` and `Project.toml`) will be stored in a directory named `SomeDir/SomeProject`. Start Julia and hit the `]` key to switch to Julia's package manager prompt (things are really easier in that mode), then type the following commands at the `...pkg>` prompt:

```julia
activate SomeDir/SomeProject
add https://github.com/emmt/InterpolationKernels.jl#v0.1
add https://github.com/emmt/LinearInterpolators.jl
```

The first command above activates the environment (and creates it if does not exists yet), the second command is to add the `InterpolationKernels` package with the restriction to use the branch `v0.1` which is the one that is compatible with the `LinearInterpolators` package which is added to your environment by the third command.  You may add any other packages.  For official packages, it is sufficient to only specify the package name (no needs to give the full URL).

To go back to the Julia prompt, just hit `^C` (control-C) or the backspace key. Unless you activate another environment or quit Julia, you will be working with the environment defined in `SomeProject`.

When you start a new Julia session, just recall the `activate SomeDir/SomeProject` command at the package manager prompt. You may also do that directly at Julia prompt (this is useful in scripts) by typing:

```julia
using Pkg
Pkg.activate("SomeDir/SomeProject")
```

Note that `SomeDir/SomeProject` is really a directory name, it may be specified using an absolute or relative path.

**Comment by assia855** [comment]
Thank you so much.
 "#v0.1 " that's  what I was looking for. It works now.
