### ISSUE TITLE
General registry?

### ISSUE THREAD

**Issue by JeffFessler** [emmt/LinearInterpolators.jl#4]
I am happy to find this package because I need an interpolator that has an adjoint.

But to build other packages on top of it confidently, I feel it would need to be in the general Julia registry
so that I can enter `[compat]` for specific versions.
Do you have a plan for registering it, e.g., after hitting certain milestones in code coverage or such?

Also, the docs link is broken right now.  Do you want a PR to help with setting up Documenter/Literate?

**Comment by emmt** [comment]
I would like to solve the following Julia issue [#41637](https://github.com/JuliaLang/julia/issues/41637) before making `LinearInterpolators` an official package.  In the mean time you can use [my personnal registry](https://github.com/emmt/EmmtRegistry):

```julia
using Pkg
pkg"registry add General"
pkg"registry add https://github.com/emmt/EmmtRegistry"
pkg"add LinearInterpolators"
```

I did not noticed that the link was broken, this is because `travis-ci.org` is ceased I have to move to `travis-ci.com`. I am not really sure I want to do that so a PR to build the the doc. by other means might be helpful.

**Comment by emmt** [comment]
The doc link is now working.  The doc is however very limited.

**Comment by JeffFessler** [comment]
Thanks for updating the docs - looks great.  And thanks for the reply about the registry plan.

I realize I can use your personal registry for my own work, but I am nearing the release of
a package that I would like to register that uses this and as far as I know it is not possible
to point to a personal registry in a Project.toml file.  I've searched but couldn't find anything.
If you happen to know if it is possible and can give a hint or pointer, I'd really appreciate it.

**Comment by emmt** [comment]
Yes it would be nice to be able to specificy other registries but I've never heard about this possibility. This may be a question to ask on Julia discourse, there is a lot of knowledge shared there and people are very helpful.

**Comment by JeffFessler** [comment]
Thanks for the suggestion.  The answer is that the Julia general registry is the only way:
https://discourse.julialang.org/t/inter-registry-dependencies/56932/5

The Julia issue you linked above looks to be "just" a performance issue.  Your package is already useful (to us at least) even with its current performance level so it sure would be great to have it registered.  I think everyone understands that it will get better as Julia performance improves.

**Comment by emmt** [comment]
OK I will add `LinearInterpolators` to the `General` registry. But `LinearInterpolators` depends on [`InterpolationKernels`](https://github.com/emmt/InterpolationKernels.jl) which is in my registry, not in `General`. So I first add `InterpolationKernels` to `General` (which, as a first registration, will take a couple of days) and then will register `LinearInterpolators` (again an additional couple of days, not taking into account that I will be in vacations).

**Comment by emmt** [comment]
BTW, the package [`InterpolationKernels`](https://github.com/emmt/InterpolationKernels.jl) has a new branch (incompatible with the current `LinearInterpolators`) with many changes and improvements. I will soon update `LinearInterpolators` to work with `InterpolationKernels` but this may introduce incompatibilities for you (the old version will remain in the 0.1 branch, while the new version will be in the 0.2 and subsequent branches). I anticipate the following changes:
- `SparseUnidimensionalInterpolator{T,S,D}` will become `SparseSeparableInterpolator{D,T,S}`. Note the different order of type parameters which is intended to **avoid type instability**.
- `TabulatedInterpolator` will be removed in favor of `SparseSeparableInterpolator` (formely `SparseUnidimensionalInterpolator` which was very similar to `TabulatedInterpolator`).
- `apply(ker::Kernel, ...)` and `apply!(dst,ker::Kernel,...)` replaced by `interpolate` and `interpolate!` to **avoid type piracy** (the `apply` and `apply!` methods are imported from [`LazyAgebra`](https://github.com/emmt/LazyAlgebra.jl) while the kernel type of `ker` is provided by [`InterpolationKernels`](https://github.com/emmt/InterpolationKernels.jl)).
- New `LazyInterpolator` and `LazySeparableInterpolator` which compute interpolation coefficients **on the fly** and thus consume almost no memory even though they are not as fast as `SparseInterpolator` and `SparseSeparableInterpolator` if applied multiple times (e.g., in iterative methods).

**Comment by JeffFessler** [comment]
Closing because it got registered - yay and thanks!
